In [1]:
# Write a Python Script that captures images from your webcam video stream
# Extracts all Faces from the image frame (using haarcascades)
# Stores the Face information into numpy arrays


In [2]:
# 1. Read and show video stream, capture images
# 2. Detect Faces and show bounding box (haarcascade) on instant face 
# 3. Flatten the largest face image(gray scale) and save in a numpy array
# 4. Repeat the above for multiple people to generate training data

In [1]:
import cv2
import numpy as np

cam = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")


In [4]:
skip = 0

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


()
()
()
()
[[251 177 121 121]]
[[252 176 120 120]]
[[253 175 125 125]]
[[251 178 121 121]]
()
()
()
()
()
[[252 178 120 120]]
[[248 176 125 125]]
()
()
()
()
()
()
()
()
()
()
[[251 183 113 113]]
[[251 183 113 113]]
[[252 186 111 111]]
()
()
()
[[248 180 120 120]]
[[248 180 120 120]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[254 182 117 117]]
()
()
()
()
()
()
()
()
()
()
[[260 184 120 120]]
[[260 184 120 120]]
()
()
()
()
()
()
()
()
()
()


In [5]:
for face in faces[-1:]:
    x,y,w,h = face
    cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)

In [ ]:
skip = 0

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    
    
    cv2.imshow("Frame",frame)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


In [ ]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data' 

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    
    
    cv2.imshow("Frame",frame)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


In [ ]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data/' 

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    #pick the last face (because it is the largest face acc. to area (f[2]*f[3]))
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
        #Extract (Crop out the required face ): Region of interest we want !!
        offset =10 #padding of 10 pixel around the face
        #Frame[Y,X]
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset] 
        face_section =cv2.resize(face_section,(100,100))
        
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data))
#     #store every 10th faces
#     if skip%10==0:
#         #store the 10 face later on 
#         pass
        
    
    
    cv2.imshow("Frame",frame)
    cv2.imshow("face section",face_section)
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

        
        
cam.release()
cv2.destroyAllWindows()


In [ ]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data/' 

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    #pick the last face (because it is the largest face acc. to area (f[2]*f[3]))
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
        #Extract (Crop out the required face ): Region of interest we want !!
        offset =10 #padding of 10 pixel around the face
        #Frame[Y,X]
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset] 
        face_section =cv2.resize(face_section,(100,100))
        
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data))
#     #store every 10th faces
#     if skip%10==0:
#         #store the 10 face later on 
#         pass
        
    
    
    cv2.imshow("Frame",frame)
    cv2.imshow("face section",face_section)
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

        
        
cam.release()
cv2.destroyAllWindows()


In [ ]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = 'data/' 

file_name=input("Enter the name of the person :")

while True:
    ret,frame = cam.read()
    
    
    if ret==False:
        continue
        
#     cv2.imshow("Frame",frame)
    
    
    
#     faces = face_cascade.detectMultiScale(frame,1.3,5)
#     print(faces)
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)



    faces = face_cascade.detectMultiScale(frame,1.3,5)
    if len(faces)==0:
        continue

    
    #make a rectangle box around faces (bounding box)
    #pick the last face (because it is the largest face acc. to area (f[2]*f[3]))
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
        #Extract (Crop out the required face ): Region of interest we want !!
        offset =10 #padding of 10 pixel around the face
        #Frame[Y,X]
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset] 
        face_section =cv2.resize(face_section,(100,100))
        
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data)) #this store and print every 10th face 
#     #store every 10th faces
#     if skip%10==0:
#         #store the 10 face later on 
#         pass
        
    
    
    cv2.imshow("Frame",frame)
    #we have took RGB img so   no. of frame x size(10000) x 3 
    cv2.imshow("face section",face_section)
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

#Convert our face list array into a numpy array
face_data =np.asanyarray(face_data)
face_data =face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)

#save this data into file system
np.save(dataset_path+file_name+".npy",face_data)

print("Data succesfully saved at "+dataset_path+file_name+".npy")
        
        
cam.release()
cv2.destroyAllWindows()


In [ ]:
#we have took RGB img so no. of frame x size(10000) x 3 


In [2]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data/' 

file_name=input("Enter the name of the person :")

while True:
    ret,frame = cam.read()
    
    
    if ret==False:
        continue
        
#     cv2.imshow("Frame",frame)
    
    
    
#     faces = face_cascade.detectMultiScale(frame,1.3,5)
#     print(faces)
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)



    faces = face_cascade.detectMultiScale(frame,1.3,5)
    if len(faces)==0:
        continue

    
    #make a rectangle box around faces (bounding box)
    #pick the last face (because it is the largest face acc. to area (f[2]*f[3]))
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
        #Extract (Crop out the required face ): Region of interest we want !!
        offset =10 #padding of 10 pixel around the face
        #Frame[Y,X]
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset] 
        face_section =cv2.resize(face_section,(100,100))
        
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data)) #this store and print every 10th face 
#     #store every 10th faces
#     if skip%10==0:
#         #store the 10 face later on 
#         pass
        
    
    
    cv2.imshow("Frame",frame)
    #we have took RGB img so   no. of frame x size(10000) x 3 
    cv2.imshow("face section",face_section)
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

#Convert our face list array into a numpy array
face_data =np.asanyarray(face_data)
face_data =face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)

#save this data into file system
np.save(dataset_path+file_name+".npy",face_data)

print("Data succesfully saved at "+dataset_path+file_name+".npy")
        
        
cam.release()
cv2.destroyAllWindows()


Enter the name of the person :aryan
1
2
3
4
5
(5, 30000)
Data succesfully saved at ./data/aryan.npy


### Final Code for - Generating Selfie Training Data using WebCam

In [2]:
import cv2
import numpy as np

cam = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")


skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data/' 

file_name=input("Enter the name of the person :")

while True:
    ret,frame = cam.read()
    
    
    if ret==False:
        continue
        
#     cv2.imshow("Frame",frame)
    
    
    
#     faces = face_cascade.detectMultiScale(frame,1.3,5)
#     print(faces)
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)



    faces = face_cascade.detectMultiScale(frame,1.3,5)
    faces=sorted(faces,key=lambda f:f[2]*f[3])
    #this is just we are sorting all faces 
    #and we can also use( ,reverse=True )reversing so big face comes ahead
    
    
    if len(faces)==0:
        continue

    
    #make a rectangle box around faces (bounding box)
    #pick the last face (because it is the largest face acc. to area (f[2]*f[3]))
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        
        #Extract (Crop out the required face ): Region of interest we want !!
        offset =10 #padding of 10 pixel around the face
        #Frame[Y,X]
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset] 
        face_section =cv2.resize(face_section,(100,100))
        
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data)) #this store and print every 10th face 
#     #store every 10th faces
#     if skip%10==0:
#         #store the 10 face later on 
#         pass
        
    
    
    cv2.imshow("Frame",frame)
    #we have took RGB img so   no. of frame x size(10000) x 3 
    cv2.imshow("face section",face_section)
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break


#step 3
#Convert our face list array into a numpy array
face_data =np.asanyarray(face_data)
face_data =face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)

#save this data into file system
np.save(dataset_path+file_name+".npy",face_data)

print("Data succesfully saved at "+dataset_path+file_name+".npy")
        
        
cam.release()
cv2.destroyAllWindows()



Enter the name of the person :aryan2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
(19, 30000)
Data succesfully saved at ./data/aryan2.npy
